GlobalMarketForcesIntelligence={}
function GlobalMarketForces:getAnalystRatingFromModifier(x) if x>=1.75 then return "Strong Buy" elseif x>=1.20 then return "Buy" elseif x>0.85 then return "Hold" elseif x>0.60 then return "Sell" end return "Strong Sell" end
function GlobalMarketForces:getFarmerOutlookFromRating(r) if r=="Strong Buy" then return "Excellent" elseif r=="Buy" then return "Good" elseif r=="Hold" then return "Average" elseif r=="Sell" then return "Poor" end return "Avoid" end
function GlobalMarketForces:getFarmerRecommendationFromOutlook(o) if o=="Excellent" then return "Aggressively Expand" elseif o=="Good" then return "Expand Production" elseif o=="Average" then return "Maintain Acreage" elseif o=="Poor" then return "Reduce Production" end return "Consider Avoiding" end
function GlobalMarketForces:getDirectionFromDelta(d) if d>=0.25 then return "Strong Upward" elseif d>=0.08 then return "Upward" elseif d<=-0.25 then return "Strong Downward" elseif d<=-0.08 then return "Downward" end return "Stable" end
function GlobalMarketForces:getMomentumLabel(d) if d=="Strong Upward" then return "Strong Uptrend" elseif d=="Upward" then return "Uptrend" elseif d=="Downward" then return "Downtrend" elseif d=="Strong Downward" then return "Strong Downtrend" end return "Stable" end
function GlobalMarketForces:getConfidenceLabelFromScore(s) if s>=90 then return "Very High" elseif s>=75 then return "High" elseif s>=55 then return "Medium" elseif s>=35 then return "Low" end return "Very Low" end
function GlobalMarketForces:getMarketConditionLabelFromScore(s) if s>=85 then return "Stable" elseif s>=65 then return "Mostly Stable" elseif s>=45 then return "Mixed" elseif s>=25 then return "Volatile" end return "Highly Volatile" end
function GlobalMarketForces:getAverageModifierForWindow(c,start,months) local last=start+months-1; local total,count=0,0; for m=start,last do total=total+self:calculateCropModifier(c,m); count=count+1 end; return count>0 and total/count or self:calculateCropModifier(c,start) end
function GlobalMarketForces:getTrendDisplayName(t,cropName) local d=t.channel=="global" and GlobalMarketForcesTrends.globalDefinitions[t.trendType] or self:getDefinitionForCropTrend(t.channel,t.trendType,cropName); return d and d.displayName or t.trendType end
function GlobalMarketForces:getTrendBaseImpact(t,cropName) local d=t.channel=="global" and GlobalMarketForcesTrends.globalDefinitions[t.trendType] or self:getDefinitionForCropTrend(t.channel,t.trendType,cropName); return d and d.baseImpact or 0 end
function GlobalMarketForces:getCropDriverLabels(c,m) local drivers,risks={},{}; for _,t in ipairs(self:getActiveGlobalTrends(m)) do table.insert(self:getTrendBaseImpact(t,c)<0 and risks or drivers,self:getTrendDisplayName(t,c)) end; for _,t in ipairs(self:getActiveCropTrends(c,m)) do local label=string.upper(string.sub(t.channel,1,1))..string.sub(t.channel,2)..": "..self:getTrendDisplayName(t,c); table.insert(self:getTrendBaseImpact(t,c)<0 and risks or drivers,label) end; for _,e in ipairs(self:getActiveEvents(m)) do local d=GlobalMarketForcesEvents.definitions[e.eventType]; local label=d and d.displayName or e.eventType; table.insert((d and d.priceDirection or 1)<0 and risks or drivers,label) end; return drivers,risks end
function GlobalMarketForces:getDynamicConfidenceScore(c,months) local m=self.market.currentMonthIndex or 1; local score=100; if months>24 then score=score-40 elseif months>6 then score=score-20 end; local events=self:getActiveEvents(m); score=score-(#events*8); local sev=0; for _,e in ipairs(events) do sev=sev+(e.severity or 0) end; score=score-math.min(20,sev*10); local pos,neg=0,0; for _,t in ipairs(self:getActiveCropTrends(c,m)) do local b=self:getTrendBaseImpact(t,c); if b>0.05 then pos=pos+1 elseif b<-0.05 then neg=neg+1 end end; if pos>0 and neg>0 then score=score-20 end; score=score-math.min(8,((GlobalMarketForcesConfig.marketProfiles[c] or {}).volatility or 0)*100); if score<0 then score=0 end; return score end
function GlobalMarketForces:getCropMarketIntelligence(c) local cur=self.market.currentMonthIndex or 1; local cm=self:calculateCropModifier(c,cur); local st,mt,lt=GlobalMarketForcesConfig.marketIntelligence.shortTermMonths,GlobalMarketForcesConfig.marketIntelligence.mediumTermMonths,GlobalMarketForcesConfig.marketIntelligence.longTermMonths; local sd=self:getDirectionFromDelta(self:getAverageModifierForWindow(c,cur,st)-cm); local md=self:getDirectionFromDelta(self:getAverageModifierForWindow(c,cur,mt)-cm); local ld=self:getDirectionFromDelta(self:getAverageModifierForWindow(c,cur,lt)-cm); local rating=self:getAnalystRatingFromModifier(cm); local out=self:getFarmerOutlookFromRating(rating); local sc=self:getDynamicConfidenceScore(c,st); local drivers,risks=self:getCropDriverLabels(c,cur); local marketType=(GlobalMarketForcesConfig.marketProfiles[c] or {}).marketType or "crop"; return {fillTypeName=c,marketType=marketType,currentModifier=cm,analystRating=rating,farmerOutlook=out,farmerRecommendation=self:getFarmerRecommendationFromOutlook(out),momentumLabel=self:getMomentumLabel(sd),shortTermDirection=sd,mediumTermDirection=md,longTermDirection=ld,forecastReliability=self:getConfidenceLabelFromScore(sc),marketCondition=self:getMarketConditionLabelFromScore(sc),drivers=drivers,risks=risks} end
function GlobalMarketForces:getMarketIntelligenceSnapshot() local rows={}; for c,_ in pairs(GlobalMarketForcesConfig.marketProfiles) do table.insert(rows,self:getCropMarketIntelligence(c)) end; local rank={Excellent=5,Good=4,Average=3,Poor=2,Avoid=1}; table.sort(rows,function(a,b) return (rank[a.farmerOutlook] or 0)>(rank[b.farmerOutlook] or 0) end); return rows end
function GlobalMarketForces:joinLabels(t,empty) if not t or #t==0 then return empty or "none" end; local s=""; for i,v in ipairs(t) do if i>1 then s=s..", " end; s=s..v end; return s end
